name: Backend CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      PORT: 4000
      NODE_ENV: test
      # SQLite for CI
      DATABASE_URL: file:./dev.db

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install deps (backend)
        working-directory: backend
        run: npm ci

      - name: Generate Prisma client
        working-directory: backend
        run: npx prisma generate --schema prisma/schema.prisma

      - name: Migrate DB
        working-directory: backend
        run: npx prisma migrate deploy --schema prisma/schema.prisma

      - name: Build server
        working-directory: backend
        run: npm run build

      - name: Start API & healthcheck
        working-directory: backend
        run: |
          node dist/server.js &
          for i in {1..30}; do
            curl -sf "http://localhost:${PORT}/api/ping" && exit 0
            sleep 1
          done
          echo "API failed to start"; exit 1
