name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: vc_user
          POSTGRES_PASSWORD: vc_pass
          POSTGRES_DB: vetcare_test
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U vc_user -d vetcare_test"
          --health-interval=5s --health-timeout=5s --health-retries=20

    env:
      DATABASE_URL: postgresql://vc_user:vc_pass@localhost:5432/vetcare_test?schema=public
      NODE_ENV: test
      CORS_ORIGIN: http://localhost:5173
      JWT_SECRET: ci_test_secret_please_change
      SMTP_FROM: noreply@ci.local

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 22 }
      - name: Install deps
        working-directory: backend
        run: npm ci
      - name: Prepare DB (migrate + generate)
        working-directory: backend
        run: |
          npx prisma migrate reset --force
          npx prisma generate
      - name: Unit tests
        working-directory: backend
        run: npm run test:unit
      - name: Integration tests
        working-directory: backend
        run: npm run test:int -- --coverage
      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-backend
          path: backend/coverage
